export function typedAction(type, payload) {
  return { type, payload };
}

export const AppActionType = {
  // Employees
  SEARCH_EMPLOYEE_LOADING: "SEARCH_EMPLOYEE_LOADING",
  SEARCH_EMPLOYEE_ERROR: "SEARCH_EMPLOYEE_ERROR",
  SEARCH_EMPLOYEE_COMPLETE: "SEARCH_EMPLOYEE_COMPLETE",

  SEARCH_EMPLOYEES_LOADING: "SEARCH_EMPLOYEES_LOADING",
  SEARCH_EMPLOYEES_ERROR: "SEARCH_EMPLOYEES_ERROR",
  SEARCH_EMPLOYEES_COMPLETE: "SEARCH_EMPLOYEES_COMPLETE",

  CREATE_EMPLOYEE_LOADING: "CREATE_EMPLOYEE_LOADING",
  CREATE_EMPLOYEE_ERROR: "CREATE_EMPLOYEE_ERROR",
  CREATE_EMPLOYEE_COMPLETE: "CREATE_EMPLOYEE_COMPLETE",

  UPDATE_EMPLOYEE_LOADING: "UPDATE_EMPLOYEE_LOADING",
  UPDATE_EMPLOYEE_ERROR: "UPDATE_EMPLOYEE_ERROR",
  UPDATE_EMPLOYEE_COMPLETE: "UPDATE_EMPLOYEE_COMPLETE",

  DELETE_EMPLOYEE_LOADING: "DELETE_EMPLOYEE_LOADING",
  DELETE_EMPLOYEE_ERROR: "DELETE_EMPLOYEE_ERROR",
  DELETE_EMPLOYEE_COMPLETE: "DELETE_EMPLOYEE_COMPLETE",
};
